# Generated by Django 4.0.1 on 2022-02-02 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('roll_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(default='', max_length=25)),
                ('attendance', models.CharField(choices=[('Absent❌', 'Absent❌'), ('Present✓', 'Present✓')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='class_10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('roll_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(default='', max_length=25)),
                ('attendance', models.CharField(choices=[('Absent❌', 'Absent❌'), ('Present✓', 'Present✓')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='class_10_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(default='', max_length=30, unique=True)),
                ('Students_name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='class_1_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(default='', max_length=30, unique=True)),
                ('Students_name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='class_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('roll_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(default='', max_length=25)),
                ('attendance', models.CharField(choices=[('Absent❌', 'Absent❌'), ('Present✓', 'Present✓')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='class_2_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(default='', max_length=30, unique=True)),
                ('Students_name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='class_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('roll_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(default='', max_length=25)),
                ('attendance', models.CharField(choices=[('Absent❌', 'Absent❌'), ('Present✓', 'Present✓')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='class_3_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(default='', max_length=30, unique=True)),
                ('Students_name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='class_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('roll_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(default='', max_length=25)),
                ('attendance', models.CharField(choices=[('Absent❌', 'Absent❌'), ('Present✓', 'Present✓')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='class_4_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(default='', max_length=30, unique=True)),
                ('Students_name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='class_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('roll_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(default='', max_length=25)),
                ('attendance', models.CharField(choices=[('Absent❌', 'Absent❌'), ('Present✓', 'Present✓')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='class_5_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(default='', max_length=30, unique=True)),
                ('Students_name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='class_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('roll_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(default='', max_length=25)),
                ('attendance', models.CharField(choices=[('Absent❌', 'Absent❌'), ('Present✓', 'Present✓')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='class_6_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(default='', max_length=30, unique=True)),
                ('Students_name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='class_7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('roll_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(default='', max_length=25)),
                ('attendance', models.CharField(choices=[('Absent❌', 'Absent❌'), ('Present✓', 'Present✓')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='class_7_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(default='', max_length=30, unique=True)),
                ('Students_name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='class_8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('roll_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(default='', max_length=25)),
                ('attendance', models.CharField(choices=[('Absent❌', 'Absent❌'), ('Present✓', 'Present✓')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='class_8_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(default='', max_length=30, unique=True)),
                ('Students_name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='class_9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('roll_no', models.IntegerField(default=0)),
                ('student_name', models.CharField(default='', max_length=25)),
                ('attendance', models.CharField(choices=[('Absent❌', 'Absent❌'), ('Present✓', 'Present✓')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='class_9_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(default='', max_length=30, unique=True)),
                ('Students_name', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Notice_Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('Notice_title', models.CharField(default='', max_length=50)),
                ('Notice_desc', models.TextField(default='')),
                ('author', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
