# Generated by Django 4.0.1 on 2022-02-02 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERVER1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_database',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
