# Generated by Django 4.0.1 on 2022-02-02 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERVER1', '0002_alter_notice_database_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_database',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 6, 50, 46, 26453)),
        ),
    ]
