# Generated by Django 4.0.1 on 2022-02-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERVER1', '0003_alter_notice_database_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_1',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='class_10',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='class_2',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='class_3',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='class_4',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='class_5',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='class_6',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='class_7',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='class_8',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='class_9',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='notice_database',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
