# Generated by Django 4.0.1 on 2022-03-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SERVER1', '0004_alter_class_1_date_alter_class_10_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('about_desc', models.TextField(default='')),
            ],
        ),
    ]
